### ISSUE TITLE
[QUESTION] Are you planning on supporting FP8?

### ISSUE THREAD

**Issue by MustafaFayez** [bytedance/flux#27]
Hi, 
Thanks for sharing this great work.

Are you planning on supporting FP8 GEMMs?

**Comment by wenlei-bao** [comment]
Yes, we do have FP8 support but only internally for now.

**Comment by MustafaFayez** [comment]
Thanks for your response.
any plans on making it public soon 😄 ?

**Comment by wenlei-bao** [comment]
@MustafaFayez not yet, but we will re-consider if there is a lot of requests on that :)
