### ISSUE TITLE
[QUESTION]How to run examples in pynvshmem

### ISSUE THREAD

**Issue by TonyWu199** [bytedance/flux#29]
Hi developers,
    I am attempting to run the `run.sh` script in pynvshmem. Firstly, I need to change `import pynvshmem` to `from flux import pynvshmem` because pynvshmem is not found, after that, i got an error as following,
```bash
[default0]:    pynvshmem.init_with_c10d_pg(TP_GROUP)
[default0]:AttributeError: module 'flux.pynvshmem' has no attribute 'init_with_c10d_pg'
```
Are there any steps I'm missing？

**Comment by wenlei-bao** [comment]
@zheng-ningxin
