### ISSUE TITLE
[QUESTION] How to use nvshmem?

### ISSUE THREAD

**Issue by chenhongyu2048** [bytedance/flux#33]
**Your question**
Ask a clear and concise question about Flux.

I'm reading the code of flux, and I noticed that in the class `AGKernelCrossNode`, if I try to use nvshmem, it will malloc memory for tensors in function `nvshmem_create_tensor_list`.   
But in the communicate function like `copy_alltoall` or `copy_ring`, it mainly use `cudaMemcpyAsync` or `ncclSend`, so I want to know will it really use nvshmem-based communication, i.e., such as nvshmem_put primitives? Or maybe there's something wrong with my understanding?

**Comment by wenlei-bao** [comment]
@chenhongyu2048 
For AG+GEMM pattern, we do use cudaMemcpyAsync or ncclSend depends on the communication scenario.
For usage of nvshmem_put related primitives, you can refer to GEMM+RS pattern for more details.

**Comment by chenhongyu2048** [comment]
Thanks for your help! I find the `nvshmemx_putmem_nbi_block` function. Maybe this is the right function for nvshmem based communication?
And for the files `src/reduce_scatter/epilogue_nvshmem_reduce_scatter.hpp` and `src/reduce_scatter/epilogue_evt_nvshmem.hpp`, which is real used?

**Comment by houqi** [comment]
> Thanks for your help! I find the `nvshmemx_putmem_nbi_block` function. Maybe this is the right function for nvshmem based communication? And for the files `src/reduce_scatter/epilogue_nvshmem_reduce_scatter.hpp` and `src/reduce_scatter/epilogue_evt_nvshmem.hpp`, which is real used?

for `AGKernelCrossNode `, none of them is used. AG+GEMM does not need to modify epilogue.

**Comment by chenhongyu2048** [comment]
Thanks. And finally I have a question: when we use ncclSend/Recv for crossnode communication in AG, will nccl comm kernel compete GPU hardware resources with GeMM compute kernel? And how does FLUX process this problem?

**Comment by chenhongyu2048** [comment]
> Thanks. And finally I have a question: when we use ncclSend/Recv for crossnode communication in AG, will nccl comm kernel compete GPU hardware resources with GeMM compute kernel? And how does FLUX process this problem?

After reading FLUX papers, my understanding is that flux just autotune Gemm tiling size to find a size with best performance?

**Comment by wenlei-bao** [comment]
> > Thanks. And finally I have a question: when we use ncclSend/Recv for crossnode communication in AG, will nccl comm kernel compete GPU hardware resources with GeMM compute kernel? And how does FLUX process this problem?
> 
> After reading FLUX papers, my understanding is that flux just autotune Gemm tiling size to find a size with best performance?

Not quite right. If you read the paper, there is a section that describe the optimizations we used.

**Comment by wenlei-bao** [comment]
> Thanks. And finally I have a question: when we use ncclSend/Recv for crossnode communication in AG, will nccl comm kernel compete GPU hardware resources with GeMM compute kernel? And how does FLUX process this problem?

Yes, it could. e.g. NCCL collectives may use different sms that affect the GEMM kernel.

Can you please open a new issue for different questions ? The title is completely unrelated now :)

**Comment by chenhongyu2048** [comment]
Thanks for your kind and patient help. I will open a new issue about the overlapping problem.
