### ISSUE TITLE
[ENHANCEMENT] support for gpu A40

### ISSUE THREAD

**Issue by 1926627357** [bytedance/flux#35]
How to use flux in gpu nodes with A40, as the current package only support for A100, A800 and H100? By the way, the intra-node A40 is connected by PCIe4.0.

**Comment by lucifer1004** [comment]
You would need to manually add `Sm86_{}` in `gemm_v2_ag_kernel.hpp`, `gemm_v2_reduce_scatter.hpp` and `gemm_v2_comm_none.hpp` at where currently is `Sm80{}`. Note that the no-nvlink support is not fully open-sourced (see #32) and the performance in certain cases might be poor.

**Comment by wenlei-bao** [comment]
Please check https://github.com/bytedance/flux/issues/32.
