### ISSUE TITLE
[QUESTION] Why is ring mode fixed to `All2All` in `src/all_gather/ths_op/all_gather_types.h`?

### ISSUE THREAD

**Issue by lucifer1004** [bytedance/flux#37]
This prevents the `--ring_mode` option in AG tests from working as expected.

By changing the function `get_ring_mode()` to simply returning its input, the `ring_mode` option can work as expected, greatly improving the performance for 8xGPUs w/o NVLink.

**Comment by houqi** [comment]
ring mode is for PCI-e machines. and there are some codes for PCI-e that are not fully tested, especially for GemmRS, and so they are not released (or open sourced).

**Comment by wenlei-bao** [comment]
@lucifer1004 We haven't yet release PCI-E support officially. We will keep you updated. For now I will close the issue.
