### ISSUE TITLE
[BUG] gemm and reduce-scatter are not overlapped 

### ISSUE THREAD

**Issue by wenscarl** [bytedance/flux#7]
**Describe the bug**
No overlap of gemm and ncclKernelReduceScatter are overlapped on the provided reduce-scatter example. The gemm kernels are on the default stream.
![image](https://github.com/bytedance/flux/assets/25590028/11e506e7-d39d-44cf-aa53-b1a22842bdd2)

**To Reproduce**
On Ampere machine with 2 GPUs, 
./scripts/launch.sh test/test_gemm_rs.py 4096 12288 49152 --dtype=float16 --iters=10

**Expected behavior**
gemms and reduce-scatter should be overlapped.

**Comment by wenscarl** [comment]
It's on A100 nvlink. Should I look at `cutlass::Kernel2<bytedance::flux::FluxGemmKernel<bytedance::flux::GemmMeta<bytedance::flux::GemmDTypeConfig<cute::C<(bytedance::flux::DataTypeEnum)1>, cute::C<(bytedance::flux::DataTypeEnum)1>` and `barrier_on_stream_kernel_threadgroup<(threadgroup_t)1>(int, int)` where the first one fuses gemm and rs and the second one is a barrier?

**Comment by wenlei-bao** [comment]
Yes. BTW you can also use --profile option. cc @zheng-ningxin

**Comment by wenscarl** [comment]
From the profile result shown above, one `FluxGemmKernel+barrier_on_stream_kernel_threadgroup` is about 65ms while `sm80_xmma_gemm_f16f16_f16f32_f32_tn_n_tilesize192x128x32_stage3_warpsize4x2x1_tensor16x8x16_kernel+ncclDevKernel_AllReduce_Sum_u8_RING_LL` is about 8.6ms. Is that normal?

**Comment by wenlei-bao** [comment]
> From the profile result shown above, one `FluxGemmKernel+barrier_on_stream_kernel_threadgroup` is about 65ms while `sm80_xmma_gemm_f16f16_f16f32_f32_tn_n_tilesize192x128x32_stage3_warpsize4x2x1_tensor16x8x16_kernel+ncclDevKernel_AllReduce_Sum_u8_RING_LL` is about 8.6ms. Is that normal?

No. The profiled result doesn't look right.
As I asked, can you please paste the whole output of the command? That report the time of Flux vs pytorch.

**Comment by wenscarl** [comment]
The full output on a A100x2 with pcie. My test was on commit 96b2e03adeee52ebcac0199b4f327e8415ce84b3.
```
# ./scripts/launch.sh test/test_gemm_rs.py 4096 12288 49152 --dtype=float16 --iters=10
torchrun --node_rank=0 --nproc_per_node=2 --nnodes=1 --rdzv_endpoint=127.0.0.1:23456 test/test_gemm_rs.py 4096 12288 49152 --dtype=float16 --iters=10
W0627 16:19:38.106000 139630205469824 torch/distributed/run.py:757]
W0627 16:19:38.106000 139630205469824 torch/distributed/run.py:757] *****************************************
W0627 16:19:38.106000 139630205469824 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
W0627 16:19:38.106000 139630205469824 torch/distributed/run.py:757] *****************************************
before pynvshmem.init_with_c10d_pg
before pynvshmem.init_with_c10d_pg
WARN: init failed for remote transport: ibrc
WARN: init failed for remote transport: ibrc
after pynvshmem.init_with_c10d_pgafter pynvshmem.init_with_c10d_pg

SOL time for GEMM(M=4096,N=12288,K=49152,TP=2): 7.929ms
torch #0: gemm 10.084 ms, comm 6.278 ms, total 16.362 ms
torch #1: gemm 9.840 ms, comm 6.517 ms, total 16.357 ms
flux  #0: gemm 20.291 ms, comm 0.407 ms, total 20.698 ms
flux  #1: gemm 20.197 ms, comm 0.500 ms, total 20.697 ms

**Comment by wenlei-bao** [comment]
> The full output on a A100x2 with pcie. My test was on commit [96b2e03](https://github.com/bytedance/flux/commit/96b2e03adeee52ebcac0199b4f327e8415ce84b3).
> 
> ```
> # ./scripts/launch.sh test/test_gemm_rs.py 4096 12288 49152 --dtype=float16 --iters=10
> torchrun --node_rank=0 --nproc_per_node=2 --nnodes=1 --rdzv_endpoint=127.0.0.1:23456 test/test_gemm_rs.py 4096 12288 49152 --dtype=float16 --iters=10
> W0627 16:19:38.106000 139630205469824 torch/distributed/run.py:757]
> W0627 16:19:38.106000 139630205469824 torch/distributed/run.py:757] *****************************************
> W0627 16:19:38.106000 139630205469824 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
> W0627 16:19:38.106000 139630205469824 torch/distributed/run.py:757] *****************************************
> before pynvshmem.init_with_c10d_pg
> before pynvshmem.init_with_c10d_pg
> WARN: init failed for remote transport: ibrc
> WARN: init failed for remote transport: ibrc
> after pynvshmem.init_with_c10d_pgafter pynvshmem.init_with_c10d_pg
> 
> SOL time for GEMM(M=4096,N=12288,K=49152,TP=2): 7.929ms
> torch #0: gemm 10.084 ms, comm 6.278 ms, total 16.362 ms
> torch #1: gemm 9.840 ms, comm 6.517 ms, total 16.357 ms
> flux  #0: gemm 20.291 ms, comm 0.407 ms, total 20.698 ms
> flux  #1: gemm 20.197 ms, comm 0.500 ms, total 20.697 ms
> ```

I thought you said NVLink. For PCIe, we haven't release PCIe support yet.

**Comment by wenscarl** [comment]
1. Is there any plan to support pattern gemm-allreduce? Or if tailored from gemm-rs + allgather, how much performance gain would be expected against nonoverlapped gemm-allreduce?
2. Is there code pointer to showcase applying flux to vllm? I think it's mentioned in the paper.

**Comment by wenlei-bao** [comment]
@wenscarl Not yet to both 1/2.

I will close this issue as the reported bug is not applied. You are welcome to open issue to continue discuss other problems.
